config/routes.rb
Rails.application.routes.draw do
  get 'recratings/create'
  get 'recratings/delete'
  get 'bookratings/create'
  get 'rooms/home'
  get 'rooms/bored'
  post 'messages', to: "messages#create"
  devise_for :users 
  post "/payments/webhook", to: "payments#webhook"
  get "/payments/success", to: "payments#success"
  resources :recommendations do
    resources :recratings
  end
  resources :booklistings do
    resources :booklistcomments
  end 
  resources :books do
    resources :bookratings    
  end
  # root 'rooms#home'
  root 'booklistings#index'
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    url = "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/booklistcomments_helper.rb
module BooklistcommentsHelper
end

app/helpers/booklistings_helper.rb
module BooklistingsHelper
end

app/helpers/bookratings_helper.rb
module BookratingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/recratings_helper.rb
module RecratingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/helper/_alert.html.erb
<%flash.each do |key,value|%>
  <div class="alert alert-<%= key%> alert-dismissible fade show" role="alert">
    <strong><%=value%></strong> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/helper/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand"><%=link_to 'BooksForAll', root_path %></div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav mr-auto">
        <%if !user_signed_in?%>
          <li class="nav-item">
            <div class="nav-link"><%= link_to 'Signup', new_user_registration_path %></div>
          </li>
        <% end %>
      </ul>
      
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <div class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            BookListing
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <ul class="dropdown-item">
              <%= link_to 'Recent Listing', booklistings_path %>
            </ul>
            <%Genre.all.each do |genre|%>
              <ul class="dropdown-item">
                <div class = "<%='active' if params[:genre]==genre.genre%>"><%= link_to genre.genre, booklistings_path(genre: genre.genre) %></div>
              </ul>
            <% end %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <div class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Books
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <ul class="dropdown-item">
              <%= link_to 'All', books_path %>
            </ul>
            <%Genre.all.each do |genre|%>
              <ul class="dropdown-item">
                <div class = "<%='active' if params[:genre]==genre.genre%>"><%= link_to genre.genre, books_path(genre: genre.genre) %></div>
              </ul>
            <% end %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <div class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Recommendations
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <ul class="dropdown-item">
              <%= link_to 'Recent Recommendations', recommendations_path %>
            </ul>
            <%Genre.all.each do |genre|%>
              <ul class="dropdown-item">
                <div class = "<%='active' if params[:genre]==genre.genre%>"><%= link_to genre.genre, recommendations_path(genre: genre.genre) %></div>
              </ul>
            <% end %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <div class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Contribute!
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <ul class="dropdown-item">
              <%= link_to 'Add a BookListing!', new_booklisting_path %>
            </ul>
            <ul class="dropdown-item">
              <%= link_to 'Add a Book', new_book_path %>
            </ul>
            <ul class="dropdown-item">
              <%= link_to 'Add a Recommendation!', new_recommendation_path %>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'ChatRoom', rooms_home_path %></div>
        </li>

        <%if user_signed_in?%>
          <li class="nav-item dropdown">
            <div class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
              <img class="avatar" src="<%= gravatar_url(current_user) %>", class="nav-link">
            </div>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <ul class="dropdown-item" , class="nav-link">
                <%= link_to 'Bored?', rooms_bored_path %>
              </ul>
              <ul class="dropdown-item" , class="nav-link">
                Profile
              </ul>
              <ul class="dropdown-item">
                <%= link_to 'Edit Account', edit_user_registration_path %>
              </ul>
              <ul class="dropdown-item">
                <%= link_to 'Logout', destroy_user_session_path, method: :delete%>
              </ul>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <div class="nav-link"><%= link_to 'Login', new_user_session_path %></div>
          </li>
        <% end %>

      </ul>
    </div>
  </nav>