config/routes.rb
Rails.application.routes.draw do
  get 'recratings/create'
  get 'recratings/delete'
  get 'bookratings/create'
  get 'rooms/home'
  get 'rooms/bored'
  post 'messages', to: "messages#create"
  devise_for :users 
  post "/payments/webhook", to: "payments#webhook"
  get "/payments/success", to: "payments#success"
  resources :recommendations do
    resources :recratings
  end
  resources :booklistings do
    resources :booklistcomments
  end 
  resources :books do
    resources :bookratings    
  end
  # root 'rooms#home'
  root 'booklistings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :picture
  belongs_to :user
  has_and_belongs_to_many :genres
  has_many :bookratings, dependent: :destroy
  paginates_per 8
end

app/models/booklistcomment.rb
class Booklistcomment < ApplicationRecord
  belongs_to :booklisting
end

app/models/booklisting.rb
class Booklisting < ApplicationRecord
  has_one_attached :picture
  belongs_to :condition
  belongs_to :user
  has_many :booklistcomments, dependent: :destroy
  has_and_belongs_to_many :genres
  paginates_per 6

  def self.search(search)
    where("title ILIKE ?", "%#{search}%") 
  end
end

app/models/bookrating.rb
class Bookrating < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :booklistings, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :booklistings, dependent: :destroy
  has_and_belongs_to_many :books, dependent: :destroy
  has_and_belongs_to_many :recommendations, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit{
    MessageBroadcastJob.perform_later(self)
  }
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  has_one_attached :picture
  belongs_to :user
  has_and_belongs_to_many :genres
  has_many :recratings, dependent: :destroy
  paginates_per 5
end

app/models/recrating.rb
class Recrating < ApplicationRecord
  belongs_to :recommendation
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
  has_many :booklistings, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :bookratings, dependent: :destroy
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]

  # Creates new books
  def index
    if params[:genre].blank?
      @books = Book.all.order("created_at DESC").page(params[:page])
    else
      @genre_id = Genre.find_by(genre: params[:genre]).id
      @books = Genre.find(@genre_id).books.all.order("created_at DESC").page(params[:page])
    end
  end

  def show
    @bookratings = Bookrating.where(book_id: @book.id).order("created_at DESC")

    # Calculate avg rating for show

    if @bookratings.blank?
      @avg_rating = 0
    else
      @avg_rating = @bookratings.average(:score).round(2)
    end
  end

  def new
    @book = current_user.books.build
  end

  def edit

  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to @book, notice: 'book was successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'book was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'book was successfully destroyed.'
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :context,:picture,:user_id,genre_ids:[])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # Creates user messages in chat

  before_action :authenticate_user!
  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.save
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Adds chat room
  def home
    @messages = Message.all
    @message = Message.new
  end
  def bored
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    url = "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/booklistings_helper.rb
module BooklistingsHelper
end

app/helpers/bookratings_helper.rb
module BookratingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/recratings_helper.rb
module RecratingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>

  <%= f.input :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %> 
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.association :genres, as: :check_boxes,collection:Genre.all.map{|g| [g.genre, g.id]}%>
  <%= f.input :context%>
  <%= f.button :submit , class:"btn btn-success"%>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1 class ="pt-5">Books</h1>

<div class="row">
    <% @books.each do |book| %>
      <div class="col-md-3 pb-5">
        <div class="card ">
          <img class="card-img-top" <%=image_tag book.picture, height: '250' if book.picture.attached? %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item text-left">
              <div><%book.genres.each do |b|%>
                <%= link_to b.genre, books_path(genre: b.genre) %>
              <% end %>
              </div>
              </li>
              <li class="list-group-item text-left">
                <%if book.bookratings.any?%>
                <%# Calculate avg rating for index %>
                <div class="star-rating" data-score= <%=(book.bookratings.map{|r| r.score}.inject{|sum, number| sum + number}/(book.bookratings.size).to_f).round(2)%>></div>
                  <% else %>
                <div class="star-rating" data-score= 0></div>
              <% end %>
              </li>
          </ul>
          <div class="card-body">
            <h5 class="card-title"><%= link_to book.title, book_path(book) %></h5>
            <p class="card-text">By: <%= book.author %></p>
            <p class="card-text"><%= truncate(book.context, length:100){link_to 'Read More', book} %></p>
            <p class="card-text"><small class="text-muted">Created <%=time_ago_in_words(book.created_at) %> Ago</small></p>
          </div>
          <div class="card-footer text-center">
            <%= link_to 'Show', book, class:"card-link" %>
            <%= link_to 'Edit', edit_book_path(book) , class:"card-link"%>
            <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class:"card-link" %>
          </div>
        </div>
      </div>   
    <% end %>
</div>
<div class="col-md-2">
  <%= link_to 'New book', new_book_path , class:"btn btn-primary"%>
</div>
<div style="display: flex; justify-content:center">
  <%=paginate @books%>
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly:  true,
    score: function(){
      return $(this).attr('data-score')
    },
    })
</script>

app/views/books/new.html.erb
<h1>Create New Book</h1>

<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="jumbotron">
<div class="row">
  <div class="col-md-4">
    <div class="text-center">
      <%=image_tag @book.picture,width: '200' if @book.picture.attached? %>
    </div>
    <hr class="my-4">
    <div class="star-rating text-center" data-score=<%=@avg_rating%>></div>
    <div class="pl-4">
      <p>
        <%= @book.title %>
      </p>
      <div>
        <strong>Genre:</strong>
        <%@book.genres.each do |b|%>
          <%= b.genre %>
        <% end %>
      </div>
      <div>
        <strong>Author:</strong>
        <%= @book.author %>
      </div>
    </div>
    </div>
  <div class="col-md-6">
    <div>
      <strong>Context:</strong>
      <%= @book.context %>
    </div>
  </div>

</div>
</div>

<div class="col-md-6 offset-md-1">
  <%if @bookratings.blank?%>
    <h2 class="pt-5">There are no reviews yet, would you like to write one?</h2>
    <% else %>
    <h2 class="pt-5" ><%= @book.bookratings.count %> Ratings</h2>
    <% @bookratings.each do |rating| %>
      <%if rating.user_id?%>
        User: <%=rating.user.username%><br>
      <% end %>
      <%# Display ratings %>
      Score: <div class="star-rating" data-score=<%=rating.score%>></div>
      Title: <%=rating.title%><br>
      Content: <%=rating.context%><br>
      <%= link_to 'Delete',[rating.book, rating], method: :delete, data: {confirm: 'Are you sure?'} %>
      <br>
    <% end %> 
  <% end %>
</div>

<div class="col-md-6 pt-5">
  <h3>Add a Rating</h3>
  <%= render 'bookratings/form' %>
</div>
<div class="col-md-6 pt-5">
  <%= link_to 'Edit', edit_book_path(@book) , class:"btn btn-dark"%> |
  <%= link_to 'Back', books_path , class:"btn btn-dark"%>
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly:  true,
    score: function(){
      return $(this).attr('data-score')
    },
    })
</script>

app/views/messages/_message.html.erb
<div class="well">
  [<%=message.created_at.strftime("%k:%M:%S %p")%>] <%= message.user.username%>:<%=message.body%>
</div>

app/views/messages/create.js.erb
$('#message_body').val('');