config/routes.rb
Rails.application.routes.draw do
  get 'recratings/create'
  get 'recratings/delete'
  get 'bookratings/create'
  get 'rooms/home'
  get 'rooms/bored'
  post 'messages', to: "messages#create"
  devise_for :users 
  post "/payments/webhook", to: "payments#webhook"
  get "/payments/success", to: "payments#success"
  resources :recommendations do
    resources :recratings
  end
  resources :booklistings do
    resources :booklistcomments
  end 
  resources :books do
    resources :bookratings    
  end
  # root 'rooms#home'
  root 'booklistings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :picture
  belongs_to :user
  has_and_belongs_to_many :genres
  has_many :bookratings, dependent: :destroy
  paginates_per 8
end

app/models/booklistcomment.rb
class Booklistcomment < ApplicationRecord
  belongs_to :booklisting
end

app/models/booklisting.rb
class Booklisting < ApplicationRecord
  has_one_attached :picture
  belongs_to :condition
  belongs_to :user
  has_many :booklistcomments, dependent: :destroy
  has_and_belongs_to_many :genres
  paginates_per 6

  def self.search(search)
    where("title ILIKE ?", "%#{search}%") 
  end
end

app/models/bookrating.rb
class Bookrating < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :booklistings, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :booklistings, dependent: :destroy
  has_and_belongs_to_many :books, dependent: :destroy
  has_and_belongs_to_many :recommendations, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit{
    MessageBroadcastJob.perform_later(self)
  }
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  has_one_attached :picture
  belongs_to :user
  has_and_belongs_to_many :genres
  has_many :recratings, dependent: :destroy
  paginates_per 5
end

app/models/recrating.rb
class Recrating < ApplicationRecord
  belongs_to :recommendation
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
  has_many :booklistings, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :bookratings, dependent: :destroy
  
end

app/controllers/booklistings_controller.rb
class BooklistingsController < ApplicationController
  before_action :set_booklisting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # Lists and sorts the booklistings
  def index
    if params[:genre].blank? && params[:search].blank?
      @booklistings = Booklisting.all.order("created_at DESC").page(params[:page])
    elsif params[:genre] 
      @genre_id = Genre.find_by(genre: params[:genre]).id
      @booklistings = Genre.find(@genre_id).booklistings.all.page(params[:page])
    elsif params[:genre] && params[:search]
      @genre_id = Genre.find_by(genre: params[:genre]).id
      @booklistings = Genre.find(@genre_id).booklistings.all.page(params[:page])
      @booklistings = @booklistings.search(params[:search])
    elsif params[:search]
      @booklistings = Booklisting.search(params[:search]).page(params[:page])
    end
  end

  def show
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      line_items: [{
          name: @booklisting.title,
          description: @booklisting.description,
          amount: @booklisting.price * 100,
          currency: 'aud',
          quantity: 1,
      }],
      payment_intent_data: {
          metadata: {
              user_id: current_user.id,
              listing_id: @booklisting.id
          }
      },
      success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@booklisting.id}",
      cancel_url: "#{root_url}listings"
  )

  @session_id = session.id
  end

  def new
    @booklisting = current_user.booklistings.build
  end

  def edit

  end

  def create
    @booklisting = current_user.booklistings.build(booklisting_params)

    if @booklisting.save
      redirect_to @booklisting, notice: 'Booklisting was successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @booklisting.update(booklisting_params)
      redirect_to @booklisting, notice: 'Booklisting was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @booklisting.destroy
    redirect_to booklistings_url, notice: 'Booklisting was successfully destroyed.'
  end

  private
    def set_booklisting
      @booklisting = Booklisting.find(params[:id])
    end

    def booklisting_params
      params.require(:booklisting).permit(:title, :author, :description, :price,:picture,:user_id,:condition_id,:search, genre_ids:[])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]

  # Creates new books
  def index
    if params[:genre].blank?
      @books = Book.all.order("created_at DESC").page(params[:page])
    else
      @genre_id = Genre.find_by(genre: params[:genre]).id
      @books = Genre.find(@genre_id).books.all.order("created_at DESC").page(params[:page])
    end
  end

  def show
    @bookratings = Bookrating.where(book_id: @book.id).order("created_at DESC")

    # Calculate avg rating for show

    if @bookratings.blank?
      @avg_rating = 0
    else
      @avg_rating = @bookratings.average(:score).round(2)
    end
  end

  def new
    @book = current_user.books.build
  end

  def edit

  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to @book, notice: 'book was successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'book was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'book was successfully destroyed.'
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :context,:picture,:user_id,genre_ids:[])
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Adds chat room
  def home
    @messages = Message.all
    @message = Message.new
  end
  def bored
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    url = "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/booklistings_helper.rb
module BooklistingsHelper
end

app/helpers/bookratings_helper.rb
module BookratingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/recratings_helper.rb
module RecratingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/booklistings/_form.html.erb
<%= simple_form_for @booklisting do |f| %>
  <% if @booklisting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booklisting.errors.count, "error") %> prohibited this booklisting from being saved:</h2>

      <ul>
      <% @booklisting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>

  <%= f.input :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %> 
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.association :genres, as: :check_boxes,collection:Genre.all.map{|g| [g.genre, g.id]}, prompt: "Select a Genre"%>
  <%= f.input :condition_id, collection: Condition.all.map{|c| [c.status, c.id]}, prompt: "Select a Condition"%>
  <%= f.input :description%>
  <%= f.input :price %> 
  <%= f.button :submit, class:"btn btn-success"  %>

<% end %>

app/views/booklistings/edit.html.erb
<h1>Editing Booklisting</h1>
<%= render 'form' %>
<%= link_to 'Back', booklistings_path %>

app/views/booklistings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Booklistings</h1>

<%= form_tag(booklistings_path, method: :get) do |f| %>
  Search By Title
  <%= text_field_tag(:search, params[:search])%>   
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<br>

  <div class="row">
      <% @booklistings.each do |booklisting| %>
        <div class="col-md-4 pb-5">
          <div class="card ">
            <img class="card-img-top" <%=image_tag booklisting.picture, height: '250' if booklisting.picture.attached? %>
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-left">
                <div><%booklisting.genres.each do |b|%>
                  <%= link_to b.genre, booklistings_path(genre: b.genre) %>
                <% end %>
                </div>
                <div class="row">
                  <div class="col-md-4">$AUS <%= booklisting.price %></div>
                  <div class="col-md-6">Condition: <%= booklisting.condition.status %></div>
                </div>
                </li>
            </ul>
            <div class="card-body">
              <h5 class="card-title"><%= link_to booklisting.title, booklisting_path(booklisting) %></h5>
              <p class="card-text">By: <%= booklisting.author %></p>
              <p class="card-text"><%= truncate(booklisting.description, length:100){link_to 'Read More', booklisting} %></p>
              <p class="card-text"><small class="text-muted">Created <%=time_ago_in_words(booklisting.created_at) %> Ago</small></p>
            </div>
            <div class="card-footer text-center">
              <%= link_to 'Show', booklisting, class:"card-link" %>
              <%= link_to 'Edit', edit_booklisting_path(booklisting) , class:"card-link"%>
              <%= link_to 'Destroy', booklisting, method: :delete, data: { confirm: 'Are you sure?' }, class:"card-link" %>
            </div>
          </div>
        </div>   
      <% end %>
  </div>
<br>
<div class="col-md-2">
  <%= link_to 'New Booklisting', new_booklisting_path, class:"btn btn-primary" %>
</div>
<div style="display: flex; justify-content:center">
  <%=paginate @booklistings%>
</div>

app/views/booklistings/new.html.erb
<h1>New Booklisting</h1>
<%= render 'form' %>
<%= link_to 'Back', booklistings_path %>

app/views/booklistings/show.html.erb
<div class="jumbotron">
<div class="row">
  <div class="col-md-6 text-center">
    <%=image_tag @booklisting.picture, width: '400' if @booklisting.picture.attached? %>
  </div>
  <hr class="my-4">
  <div class="col-md-6 pl-5">
    <div style="font-size: 25px;">
      <strong style="font-weight">Title:</strong>
      <%= @booklisting.title %>
    </div>
    <div>
      <strong>Condition:</strong>
      <%= @booklisting.condition.status %>
    </div>
    <div>
      <strong>Posted By:</strong>
      <%= @booklisting.user.username %>
    </div>
    <div>
      <strong>Author:</strong>
      <%= @booklisting.author %>
    </div>
    <div>
      <div>Genre</div>
      <%@booklisting.genres.each do |b|%>
        <%= b.genre %>
      <% end %>
    </div>
    <div>
      <strong>Description:</strong>
      <%= @booklisting.description %>
    </div>

    <div class="pb-2">
      <strong>Price:</strong>
      <%= @booklisting.price %>
    </div>
    <button data-stripe="payment" class="btn btn-primary">
      Buy Book <%= number_to_currency(@booklisting.price) %>
    </button>
    </div>
    </div>
</div>
<br>
<br>

<h3 class = "col-md-6 offset-md-1"><%= @booklisting.booklistcomments.count %> Comments</h3>

<%= render @booklisting.booklistcomments %>

<div class="col-md-6 pt-5">
  <h2>Add a Comment</h2>
  <%= render 'booklistcomments/form' %>
</div>
<div class="col-md-6 pt-5">
  <%= link_to 'Edit', edit_booklisting_path(@booklisting) , class:"btn btn-dark"%> |
  <%= link_to 'Back', booklistings_path, class:"btn btn-dark" %>
</div>
<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>